version: 0.0
os: linux
files:
  - source: config
    destination: /home/flex/codedeploy_config
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: flex
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: flex
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: flex
  ValidateService:
    - location: validate_service.sh
      timeout: 300
      runas: flex

